import rclpy
from rclpy.node import Node
from rclpy.qos import QoSProfile, ReliabilityPolicy, DurabilityPolicy
from geometry_msgs.msg import Twist
from sensor_msgs.msg import Imu
from std_msgs.msg import Bool
import time
import threading
from pymavlink import mavutil
import numpy as np
from scipy.spatial.transform import Rotation
from geometry_msgs.msg import Vector3
from std_msgs import float32
from custom_messages.msg import Slow
from custom_messages.msg import ImuBundled
import math, time
from math import sin, cos, tan


# publishes an estimate as to the robot's heading - 0 is north, ranges from -pi to pi, 
# ordered in counterclockwise fashion
class ImuPoseEstimate(Node):
    def __init__(self):
        super().__init__('rover_node')
        self.previous_time = time.time()
        self.roll_rad = 0.0
        self.pitch_rad = 0.0
        self.yaw_rad = 0.0
        # Subscribers - MARY consider appending a timestamp for more accurate time estimates
        # versus late estimates
        queue_size = 100
        self.cmd_sub = self.create_subscription(
            Vector3, 'imu/gyro', self.imu_gyro, queue_size)
        self.imu_sub = self.create_subscription(ImuBundled, 'imu/imu_bundled', self.change_in_state_callback, queue_size)
        self.heading_estimate_pub = self.create_publisher(float32, 'imu/heading_estimate', queue_size)


    def normalize_angle(self, angle_rad):
        if angle_rad > 2*math.pi:
            angle_rad -= 2*math.pi 
        if angle_rad < 0:
            angle_rad += 2*math.pi
        return angle_rad

    def update_euler_angles(self, angles_rad):
        self.roll = angles_rad[0] 
        self.pitch = angles_rad[1] 
        self.yaw = angles_rad[2]
        
    def update_angles_from_euler_angles(self, angles_rad):
        angles_rad[0] = self.roll 
        angles_rad[1] = self.pitch 
        angles_rad[2] = self.yaw
        return angles_rad
    
    def convert_angle_to_lidar_heading(self, angle):
        angle = angle - math.pi/2
        # normalize to -pi to pi
        if angle > math.pi:
            angle -= 2*math.pi 
        if angle < -math.pi:
            angle += 2*math.pi

    def imu_callback(self, msg: ImuBundled):
        current_time = time.time()
        dt = current_time - self.previous_time
        self.previous_time = current_time
        g = -9.8
        w = .98

        # collect data values

        # mary potential the accel has been scaled appropriately
        accel = msg.accel
        gyro = msg.gyro
        pqr = np.array([gyro.x, gyro.y, gyro.z])
        a = np.array([accel.x, accel.y, accel.z])


        # euler rates - conversion from pqr
        angles_dot = np.zeros((3, 1))
        
        # final euler angles
        # include our initial value
        angles = np.zeros((3, 2))

        angles[:,0] = self.update_angles_from_euler_angles(angles[:, 0])

        

        # euler angles generated by acceleration
        angles_a = np.array([0.0, 0.0, 0.0])


        # estimate next angles from acceleration

        # roll 
        angles_a[0] = math.atan2(a[1], a[2])

        # pitch
        angles_a[1] = math.asin(a[0]/g)

        # previous angles
        phi = angles[0]
        theta = angles[1]

        # rates of previous t
        # assuming no theta pi/2
        mat = np.array([[1, sin(phi)*tan(theta), cos(phi)*tan(theta)],
                        [0, cos(phi), -sin(phi)],
                        [0, sin(phi)/cos(theta), cos(phi)/cos(theta)]])
        
        # calculate euler rates - estimation with previous angles
        angles_dot[:, 0] = np.matmul(mat, pqr) 


        # make sure the psi value is the same as from integrated euler rate
        angles_a[2] = angles_dot[2]*dt + angles[2]


        angles[:,1] = (angles_dot[:, 0]*dt + angles)*w + (1-w)*angles_a


        self.update_euler_angles(angles[:,1])
        self.heading_estimate_pub(self.convert_angle_to_lidar_heading (self.normalize_angle(self.yaw)))

        return
        

        """
            Generates an estimate in change in state based on complementary filter 
            on both imu gyro data and imu acceleration data
        """
    def change_in_state_callback(self):




def main(args=None):
    rclpy.init(args=args)
    
    try:
        node = ImuPoseEstimate()
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        if 'node' in locals():
            node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
