joy_node:
  ros__parameters:
    dev: "/dev/input/js0"
    deadzone: 0.3

teleop_twist_joy_node:
  ros__parameters:
    enable_button: 7
    axis_linear:
      x: 1
    scale_linear:
      x: 0.7
    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 0.6
